import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { HeroAvatar } from './HeroAvatar';
export function AvatarCarousel({ children, selectedIndex, onSelect }) {
    if (children.length === 0) {
        return (_jsx("p", { className: "text-slate-400 text-center text-lg", children: "No heroes found. Ask your parent to add you!" }));
    }
    const selected = children[selectedIndex];
    return (_jsxs("div", { className: "flex flex-col items-center gap-4", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("button", { type: "button", onClick: () => onSelect((selectedIndex - 1 + children.length) % children.length), className: "w-12 h-12 rounded-full bg-slate-700 hover:bg-slate-600 text-white text-2xl\n                     flex items-center justify-center active:scale-90 transition-transform\n                     disabled:opacity-30", disabled: children.length <= 1, "aria-label": "Previous hero", children: "\u2039" }), _jsx(AnimatePresence, { mode: "wait", children: _jsx(motion.div, { initial: { opacity: 0, scale: 0.8 }, animate: { opacity: 1, scale: 1 }, exit: { opacity: 0, scale: 0.8 }, transition: { duration: 0.25 }, className: "flex flex-col items-center", children: _jsx("div", { className: "rounded-full bg-slate-800 border-4 border-hero-amber p-3 shadow-lg shadow-hero-amber/20", children: _jsx(HeroAvatar, { costume: selected.avatarConfig.costume, mask: selected.avatarConfig.mask, size: 100, animate: true }) }) }, selected.id) }), _jsx("button", { type: "button", onClick: () => onSelect((selectedIndex + 1) % children.length), className: "w-12 h-12 rounded-full bg-slate-700 hover:bg-slate-600 text-white text-2xl\n                     flex items-center justify-center active:scale-90 transition-transform\n                     disabled:opacity-30", disabled: children.length <= 1, "aria-label": "Next hero", children: "\u203A" })] }), _jsx(AnimatePresence, { mode: "wait", children: _jsx(motion.p, { initial: { opacity: 0, y: 8 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -8 }, className: "text-2xl font-hero text-hero-amber tracking-wide", children: selected.heroName }, selected.id) }), children.length > 1 && (_jsx("div", { className: "flex gap-2", children: children.map((child, i) => (_jsx("button", { type: "button", onClick: () => onSelect(i), className: `w-3 h-3 rounded-full transition-colors ${i === selectedIndex ? 'bg-hero-amber' : 'bg-slate-600'}`, "aria-label": `Select ${child.heroName}` }, child.id))) }))] }));
}
